#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DEBUG=0
SENT=0

_help() {
  cat << EOF

Redeliver Most Recent GitHub Close PR Webhook Delivery for this branch.

USAGE
  gh redeliver-webhook-pr-close <webhook-url> [flags]

FLAGS
  --dry-run   Do not actually redeliver, just print what would be done.
EOF
}

_get_pr_id() {
  gh pr view --json number --jq '.number'
}

main() {
  local positional_args=""

  while (( "$#" )); do
    case "${1-}" in
      --help|-h)
        # flag --help or -h
        _help
        exit 1;
        ;;
      --dry-run|-dry-run)
        # flag --dry-run
        local dry_run=true
        ;;
      --*|-* )
        echo "Error: Unsupported option '${1:-}'. Use --help for usage information." >&2
        exit 1
        ;;
      *)
        # Not a flag nor parameter, must be positional argument.
        positional_args="$positional_args '$1'"
    esac
    shift
  done

  # Update positional arguments to exclude options.
  eval set -- "$positional_args"

  if [[ "$#" == 0 ]]; then
    # No position arguments given.
    _help
    exit 1;
  fi

  # Get (most recent) PR Id associated with the current branch.
  #
  # Note: Even if the branch name has multiple PRs associated with it,
  # (e.g. one PR into develop and one into main both from this branch)
  # only the most recent (highest) PR ID is returned.
  PR_ID=$(_get_pr_id);

  # Get ID associated with Webhook URL.
  WEBHOOK_ID=$(gh api "/repos/{owner}/{repo}/hooks" --jq ".[] | select(.config.url==\"$1\") | .id");

  if [[ -z "$WEBHOOK_ID" ]]; then
    echo "No webhook found for URL $1";
    exit 1;
  fi

  if [[ $DEBUG -eq 1 ]]; then
    echo "Webhook ID $WEBHOOK_ID"
  fi

  # Get deliveries associated with the Webhook ID.
  DELIVERY_IDS=$(gh api /repos/{owner}/{repo}/hooks/"$WEBHOOK_ID"/deliveries --jq 'map(select(.event=="pull_request")) | map(select(.action=="closed")) | .[].id');

  if [[ $DEBUG -eq 1 ]]; then
    echo "Delivery IDs: $DELIVERY_IDS"
  fi

  for DELIVERY_ID in $DELIVERY_IDS; do
    if [[ $DEBUG -eq 1 ]]; then
      echo "Delivery ID: $DELIVERY_ID"
    fi
    DELIVERY_REQUEST_PR_NUMBER=$(gh api "/repos/{owner}/{repo}/hooks/$WEBHOOK_ID/deliveries/$DELIVERY_ID" --jq '.request.payload.pull_request.number');
    if [[ $DEBUG -eq 1 ]]; then
      echo "Delivery Request PR Number: $DELIVERY_REQUEST_PR_NUMBER"
    fi
    if [[ "$DELIVERY_REQUEST_PR_NUMBER" == "$PR_ID" ]]; then
      echo
      echo "Redeliver Close PR #$PR_ID Delivery ($DELIVERY_ID) to Webhook $WEBHOOK_ID ($1)";
      if [ "${dry_run:-false}" = true ]; then
        echo "Dry run mode, no delivery made";
      else
        gh api --method POST "/repos/{owner}/{repo}/hooks/$WEBHOOK_ID/deliveries/$DELIVERY_ID/attempts";
      fi
      SENT=1;
      break
    else
      if [[ $DEBUG -eq 1 ]]; then
        echo "Skipping Delivery ID: $DELIVERY_ID (PR ID does not match)"
      fi
    fi
  done;

  if [[ $SENT -eq 0 ]]; then
    echo "No matching webhook deliveries found for PR #$PR_ID";
    exit 1;
  fi
}

main "$@"
